dracut-ng: update-initramfs: abort if one or more jobs failed
Signed-off-by: Xinhui Yang <cyan@cyano.uk>

diff --git a/app-admin/dracut-ng/autobuild/overrides/usr/bin/update-initramfs b/app-admin/dracut-ng/autobuild/overrides/usr/bin/update-initramfs
--- a/app-admin/dracut-ng/autobuild/overrides/usr/bin/update-initramfs
+++ b/app-admin/dracut-ng/autobuild/overrides/usr/bin/update-initramfs
@@ -5,6 +5,9 @@ if [ "$EUID" -ne 0 ]; then
 	exit
 fi
 
+# The return status of GNU parallel.
+parallel_status=0
+
 # $1 = single|parallel   - whether initrd generation is in parallel
 #      single   = print message at start
 #      parallel = print completion notice or error message
@@ -20,9 +23,11 @@ generate_initrd_if_needed() {
 		if [[ "$mode" == "parallel" ]]; then
 			if [[ $dracut_ret -eq 0 ]]; then
 				echo -e "Successfully generated initrd."
+				return 0
 			else
 				echo -e "\033[31mDracut returned non-zero exit code $dracut_ret.\033[0m"
 				echo -e "\033[31mSee messages for details.\033[0m"
+				return 1
 			fi
 		fi
 	else
@@ -31,8 +36,9 @@ generate_initrd_if_needed() {
 		else
 			echo -e "\033[33m**\033[0m\tSkipping incomplete kernel modules tree $version ..."
 		fi
+		return 0
 	fi
-
+	return $dracut_ret
 }
 
 export -f generate_initrd_if_needed
@@ -45,9 +51,11 @@ if [ -x /usr/bin/dracut ]; then
 			echo -e "\033[36m**\033[0m\tGenerating initrd (Initialization RAM Disk) for $(echo ${task_list} | wc -w) kernel versions ..."
 			parallel \
 				--tmpdir=/var/cache/dracut \
+				--halt-on-error soon,fail=1 \
 				--will-cite \
 				--tagstring '{=$_=$_ . " " x (20 - length($_))=}' \
 				generate_initrd_if_needed parallel ::: ${task_list}
+			parallel_status=$?
 		else
 			echo -e "\033[36m**\033[0m\tNo kernel module tree found, skipping generation."
 		fi
@@ -59,6 +67,11 @@ if [ -x /usr/bin/dracut ]; then
 	fi
 else
 	echo -e "\033[33m**\033[0m\tCommand \"dracut\" is not installed, skipping generation.\n\tYou may not be able to boot the new kernel on the next boot."
+fi
+
+if [ "x$parallel_status" != "x0" ] ; then
+	echo -e "\033[33m**\033[0m\tOne or more jobs have failed, aborting.\n\tSee the output above for details."
+	exit 1
 fi
 
 # Notify bootloader
