linuxsampler: move VST SDK download to spec

diff --git a/extra-multimedia/linuxsampler/autobuild/prepare b/extra-multimedia/linuxsampler/autobuild/prepare
--- a/extra-multimedia/linuxsampler/autobuild/prepare
+++ b/extra-multimedia/linuxsampler/autobuild/prepare
@@ -1,6 +1,4 @@
-wget "https://www.steinberg.net/sdk_downloads/vstsdk367_03_03_2017_build_352.zip"
-echo -n "[INFO] Decompressing VST SDK... "
-bsdtar -xf vstsdk367_03_03_2017_build_352.zip
-( [ -d "$(pwd)/VST_SDK/VST3_SDK" ] && echo "OK!" ) || ( echo "error: VST directory structure has changed!" ; exit 1; )
-echo -n "[INFO] Copying VST 2 SDK onto VST 3 compatibility layer... "
-( cp -r "$(pwd)/VST_SDK/VST2_SDK/"* "$(pwd)/VST_SDK/VST3_SDK" && echo "OK!" ) || ( echo "error: Copy operation failed!" ; exit 1; )
+abinfo "Decompressing VST SDK ..."
+( [ -d "$SRCDIR/../VST_SDK/VST3_SDK" ] && echo "OK!" ) || ( echo "error: VST directory structure has changed!" ; exit 1; )
+abinfo "Copying VST 2 SDK onto VST 3 compatibility layer... "
+( cp -r "$SRCDIR/../VST_SDK/VST2_SDK/"* "$SRCDIR/../VST_SDK/VST3_SDK" && echo "OK!" ) || ( echo "error: Copy operation failed!" ; exit 1; )
