kernel-tools: (mips64r6el) disable rtla/latency
FIXME: Fails to build on MIPS R6 due to missing __NR_sched_getattr.

diff --git a/app-admin/kernel-tools/autobuild/build b/app-admin/kernel-tools/autobuild/build
--- a/app-admin/kernel-tools/autobuild/build
+++ b/app-admin/kernel-tools/autobuild/build
@@ -63,10 +63,13 @@ cd "$SRCDIR"/tools/iio
 make
 make install INSTALL_ROOT="$PKGDIR"
 
-# tracing rtla / lantency
-cd "$SRCDIR"/tools/tracing
-make
-make install PREFIX=/usr sbindir="/usr/bin" MANDIR="/usr/share/man" DESTDIR="$PKGDIR"
+# FIXME: Fails to build on MIPS R6 due to missing __NR_sched_getattr.
+if ! ab_match_arch mips64r6el; then
+    # tracing rtla / lantency
+    cd "$SRCDIR"/tools/tracing
+    make
+    make install PREFIX=/usr sbindir="/usr/bin" MANDIR="/usr/share/man" DESTDIR="$PKGDIR"
+fi
 
 # gpio
 cd "$SRCDIR"/tools/gpio
