kernel-tools: (loongson3,riscv64) disable latency/rtla
FIXME: Fails to build on loongson3, mips64r6el, riscv64 due to missing
__NR_sched_getattr

diff --git a/app-admin/kernel-tools/autobuild/build b/app-admin/kernel-tools/autobuild/build
--- a/app-admin/kernel-tools/autobuild/build
+++ b/app-admin/kernel-tools/autobuild/build
@@ -63,8 +63,11 @@ cd "$SRCDIR"/tools/iio
 make
 make install INSTALL_ROOT="$PKGDIR"
 
-# FIXME: Fails to build on MIPS R6 due to missing __NR_sched_getattr.
-if ! ab_match_arch mips64r6el; then
+# FIXME: Fails to build on loongson3, mips64r6el, riscv64 due to missing
+# __NR_sched_getattr.
+if ! ab_match_arch loongson3 && \
+   ! ab_match_arch mips64r6el && \
+   ! ab_match_arch riscv64; then
     # tracing rtla / lantency
     cd "$SRCDIR"/tools/tracing
     make
