firefox: use BFD instead of LLD on Loongson 3
Also disable wasm sandboxing.

diff --git a/app-web/firefox/autobuild/prepare b/app-web/firefox/autobuild/prepare
--- a/app-web/firefox/autobuild/prepare
+++ b/app-web/firefox/autobuild/prepare
@@ -8,10 +8,27 @@ abinfo "Preparing mozconfig ..."
 sed -e "s,@HOST@,${ARCH_TARGET[${CROSS:-ARCH}]},g" \
     -i "$SRCDIR"/autobuild/mozconfig
 
-echo "ac_add_options --enable-linker=lld" \
-    >> "$SRCDIR"/autobuild/mozconfig
-echo "ac_add_options --with-wasi-sysroot=/usr/lib/wasm32-wasi/" \
-    >> "$SRCDIR"/autobuild/mozconfig
+if ! ab_match_arch loongson3; then
+    echo "ac_add_options --enable-linker=lld" \
+        >> "$SRCDIR"/autobuild/mozconfig
+    echo "ac_add_options --with-wasi-sysroot=/usr/lib/wasm32-wasi/" \
+        >> "$SRCDIR"/autobuild/mozconfig
+fi
+
+# FIXME
+# error: linking with `/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/build/cargo-linker` failed: exit status: 1
+#   |
+#   = note: LC_ALL="C" PATH="/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/bin:/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/mozbuild/srcdirs/firefox-128.0.2-cd118c606d13/_virtualenvs/build/bin:/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/mozbuild/srcdirs/firefox-128.0.2-cd118c606d13/_virtualenvs/mach/bin:/usr/local/bin:/usr/bin:/root/.cargo/bin" VSLANG="1033" "/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/build/cargo-linker" "/tmp/rustcNfYF5C/symbols.o" "/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/build/proc-macro2-2e9eccf43e42a20c/build_script_build-2e9eccf43e42a20c.build_script_build.7fc36fe6be68b652-cgu.0.rcgu.o" "/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/build/proc-macro2-2e9eccf43e42a20c/build_script_build-2e9eccf43e42a20c.build_script_build.7fc36fe6be68b652-cgu.1.rcgu.o" "/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/build/proc-macro2-2e9eccf43e42a20c/build_script_build-2e9eccf43e42a20c.46klksw3d6aqgnt6.rcgu.o" "-Wl,--as-needed" "-L" "/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/deps" "-L" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib" "-Wl,-Bstatic" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libstd-6dcaeb4e3195ef4c.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libpanic_unwind-3b492db5f861c144.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libobject-a4d15655b8d59547.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libmemchr-433eb4217c15c220.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libaddr2line-3694f367f2cdb9fc.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libgimli-73fb45a729ed0e30.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/librustc_demangle-41cacb4ff97fa4cf.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libstd_detect-73d35a69185f39da.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libhashbrown-f5654efde69fe63a.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/librustc_std_workspace_alloc-d553094a352c860a.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libminiz_oxide-660efaccb5d68a60.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libadler-b79bbf5dab20e247.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libunwind-12f55669c7956981.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libcfg_if-098c3160b34fea81.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/liblibc-9879917f39f4f518.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/liballoc-0695d1b670b70049.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/librustc_std_workspace_core-b92546fd4bf9da36.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libcore-306fddc16bfa4696.rlib" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib/libcompiler_builtins-609434335fac640f.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib64/rustlib/mips64el-unknown-linux-gnuabi64/lib" "-o" "/var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/build/proc-macro2-2e9eccf43e42a20c/build_script_build-2e9eccf43e42a20c" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,--strip-debug" "-nodefaultlibs"
+#   = note: ld.lld: error: relocation R_MIPS_64 cannot be used against symbol 'DW.ref.rust_eh_personality'; recompile with -fPIC
+#           >>> defined in /var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/build/proc-macro2-2e9eccf43e42a20c/build_script_build-2e9eccf43e42a20c.build_script_build.7fc36fe6be68b652-cgu.0.rcgu.o
+#           >>> referenced by build_script_build.7fc36fe6be68b652-cgu.0
+#           >>>               /var/cache/acbs/build/acbs.tdg5m00_/firefox-128.0.2/obj-mips64el-unknown-linux-gnuabi64/release/build/proc-macro2-2e9eccf43e42a20c/build_script_build-2e9eccf43e42a20c.build_script_build.7fc36fe6be68b652-cgu.0.rcgu.o:(.eh_frame+0x4103)
+if ab_match_arch loongson3; then
+    echo "ac_add_options --enable-linker=bfd" \
+        >> "$SRCDIR"/autobuild/mozconfig
+    echo "ac_add_options --without-wasm-sandboxed-libraries" \
+        >> "$SRCDIR"/autobuild/mozconfig
+fi
 
 if ab_match_arch ppc64el; then
     abinfo "FIXME: Disabling broken WebRTC on ppc64el ..."
