liblol: add host-gtk2

diff --git a/app-emulation/liblol/autobuild/additional-files/hooks/postinst.in b/app-emulation/liblol/autobuild/additional-files/hooks/postinst.in
--- a/app-emulation/liblol/autobuild/additional-files/hooks/postinst.in
+++ b/app-emulation/liblol/autobuild/additional-files/hooks/postinst.in
@@ -15,3 +15,17 @@ if [ -d "$GDK_PIXBUF_LOADERS_DIR" ]; then
         echo "Please run '$GDK_PIXBUF_UPDATER --update-cache' manually after loading" >&2
     fi
 fi
+
+GTK2_IM_DIR=@prefix@/lib/@target@/gtk-2.0/2.10.0/immodules
+GTK2_IM_UPDATER=@prefix@/lib/@target@/libgtk2.0-0/gtk-query-immodules-2.0
+
+if [ -d "$GTK2_IM_DIR" ]; then
+    echo "Updating gtk2 immodules cache..." >&2
+    if ! "$GTK2_IM_UPDATER" --update-cache; then
+        echo "Failed to update gtk2 immodules cache." >&2
+        echo "It might be caused by not loading the old world compatibility module." >&2
+        cp -f "/usr/share/liblol/gtk2-immodules.cache.default" "@prefix@/lib/@target@/gtk-2.0/2.10.0/immodules.cache"
+        echo "I have copied the default cache file" >&2
+        echo "Please run '$GTK2_IM_UPDATER --update-cache' manually after loading" >&2
+    fi
+fi
