lmms: more optimized build

diff --git a/extra-creativity/lmms/autobuild/patch b/extra-creativity/lmms/autobuild/patch
--- a/extra-creativity/lmms/autobuild/patch
+++ b/extra-creativity/lmms/autobuild/patch
@@ -1,2 +1,13 @@
 sed -i 's|lib64|lib|g' cmake/modules/DetectMachine.cmake
 sed -i 's/MODULE/SHARED/g' cmake/modules/BuildPlugin.cmake #for workaround VST bugs
+
+for i in autobuild/patches/*; do
+    echo "[INFO] Applying ${i}..."
+    if ! patch -Np1 -i "$(readlink -f ${i})"; then
+        echo "[ERROR] Failed to apply patch!"
+        exit 1
+    fi
+done
+echo "[INFO] Generating LMMS staff roll..."
+git shortlog -nse | cut -f 2- > doc/CONTRIBUTORS
+
